version: "3.7"
services:
  app:
    build:
      context: ./prod
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:80"   # http
      - "8443:443"   # https
    links:
      - db

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - simpleHomeData:/var/lib/mysql

volumes:
  simpleHomeData:
