version: "3.7"
services:
  app:
    build:
      context: ./prod
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:80"   # apache
    networks:
      default:
        ipv4_address: 173.20.0.2

    extra_hosts:
      - "dockerhost:173.20.0.1"


networks:
  default:
    name: simple_home_network
    ipam:
      driver: default
      config:
        - subnet: 173.20.0.0/16

volumes:
  simpleHomeData:
