version: "3.7"
services:
  app:
    build:
      context: ./dev
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:80"   # http
      - "8443:443"  # https
      - "3000:3000" # browsersync
      - "3001:3001" # browsersync ui
      - "5858:5858" # npm debug
      - "7000:7000" # npm debug
    links:
      - db
      - smtp
    networks:
      default:
        ipv4_address: 173.20.0.2
    volumes:
      - ../simple-home:/app
    environment:
      PHP_IDE_CONFIG: "serverName=simplehome"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=173.20.0.1 idekey=PHPSTORM"
      PHP_MAX_EXECUTION_TIME: 3600
      #XDEBUG_MODE: "profile"
      #XDEBUG_OUTPUT_DIR: "/app/storage/xdebug-profiles"
      #XDEBUG_PROFILER_ENABLE: "true"
      #XDEBUG_PROFILER_ENABLE_TRIGGER_VALUE: "PHPSTORM"

    extra_hosts:
      - "dockerhost:173.20.0.1"
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: simplehome
      MYSQL_DATABASE: simplehome
      MYSQL_USER: simplehome
      MYSQL_PASSWORD: simplehome
    ports:
      - "3308:3306"
    networks:
      default:
        ipv4_address: 173.20.0.3
    volumes:
      - simpleHomeData:/var/lib/mysql
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      default:
        ipv4_address: 173.20.0.4


networks:
  default:
    name: simple_home_network
    ipam:
      driver: default
      config:
        - subnet: 173.20.0.0/16

volumes:
  simpleHomeData:
